export default [
  {
    exact: true,
    path: '/login',
    component: '@/layouts/AuthLayout/index',
    title: 'Login',
    wrappers: ['@/layouts/Wrapper'],
    routes: [{ exact: true, path: '/login', component: '@/pages/Login/index' }],
  },
  {
    exact: false,
    path: '/',
    component: '@/layouts/MainLayout',
    wrappers: ['@/layouts/Wrapper'],
    routes: [
      {
        exact: true,
        path: '/profile',
        component: '@/pages/Profile/index',
        title: 'navbar.Profile',
        routes: [],
        wrappers: ['@/layouts/Wrapper'],
      },
      {
        exact: true,
        path: '/user',
        component: '@/pages/User/index',
        title: 'navbar.Profile',
        routes: [],
        wrappers: ['@/layouts/Wrapper'],
      },
      {
        exact: true,
        path: '/kyc',
        component: '@/pages/Kyc/index',
        title: 'navbar.Profile',
        routes: [],
        wrappers: ['@/layouts/Wrapper'],
      },
      {
        exact: true,
        path: '/admin',
        component: '@/pages/Admin/index',
        title: 'navbar.Profile',
        routes: [],
        wrappers: ['@/layouts/Wrapper'],
      },
      {
        exact: true,
        path: '/bike-station',
        component: '@/pages/bikeStation/index',
        title: 'navbar.Profile',
        routes: [],
        wrappers: ['@/layouts/Wrapper'],
      },
      {
        exact: true,
        path: '/admin_account',
        component: '@/pages/AdminAccount/index',
        title: 'navbar.Profile',
      },
      {
        exact: true,
        path: '/vehicles',
        component: '@/pages/Vehicle/index',
        title: 'navbar.Profile',
      },
      {
        exact: true,
        path: '/lock',
        component: '@/pages/Locks/index',
        title: 'navbar.Profile',
      },
      {
        exact: true,
        path: '/travel',
        component: '@/pages/Travel/index',
        title: 'navbar.Profile',
      },
      {
        exact: true,
        path: '/user_wallet',
        component: '@/pages/UserWallet/index',
        title: 'navbar.Profile',
      },
      {
        exact: true,
        path: '/ticket',
        component: '@/pages/Ticket/index',
        title: 'navbar.Profile',
      },
      {
        exact: true,
        path: '/payment_method',
        component: '@/pages/PaymentMethod/index',
        title: 'navbar.Profile',
      },
      {
        exact: true,
        path: '/promotion',
        component: '@/pages/Promotion/index',
        title: 'navbar.Profile',
      },
      {
        exact: true,
        path: '/tutorial',
        component: '@/pages/Tutorial/index',
        title: 'navbar.Profile',
      },
      {
        exact: true,
        path: '/news',
        component: '@/pages/News/index',
        title: 'navbar.Profile',
      },
      {
        exact: true,
        path: '/rate',
        component: '@/pages/Rate/index',
        title: 'navbar.Profile',
      },
    ],
  },
];
